using Verse;
using RimWorld;
using HarmonyLib;
using System.Collections.Generic;
using DiseasesFramework.InfectionVectors.DF_Ingestion;

namespace DiseasesFramework.HarmonyPatches
{
    /// <summary>
    /// Harmony patch for GenRecipe.MakeRecipeProducts.
    /// Intercepts the moment a recipe (like butchering or cooking) produces items 
    /// to check if they should be contaminated by the worker's current diseases.
    /// </summary>
    [HarmonyPatch(typeof(GenRecipe), "MakeRecipeProducts")]
    public static class Patch_GenRecipe_MakeRecipeProducts
    {
        /// <summary>
        /// Postfix that iterates through the generated products of a recipe.
        /// If the worker carries an 'IngestionContagion' disease, it attempts to infect the resulting items.
        /// </summary>
        /// <param name="values">The collection of products generated by the recipe.</param>
        /// <param name="recipeDef">The definition of the recipe being executed.</param>
        /// <param name="worker">The pawn performing the task.</param>
        /// <returns>The original products, potentially modified with contamination data.</returns>
        public static IEnumerable<Thing> Postfix(IEnumerable<Thing> values, RecipeDef recipeDef, Pawn worker)
        {
            // Initial safety check: ensure the worker exists and is biological.
            if (worker == null || !worker.RaceProps.IsFlesh)
            {
                foreach (Thing t in values) yield return t;
                yield break;
            }

            HediffComp_IngestionContagion contagionComp = null;
            var hediffs = worker.health.hediffSet.hediffs;

            // Scan the worker's health for any disease marked as transmissible via ingestion.
            for (int i = 0; i < hediffs.Count; i++)
            {
                var c = hediffs[i].TryGetComp<HediffComp_IngestionContagion>();
                if (c != null)
                {
                    contagionComp = c;
                    break; // For balance, we take the first matching contagion component found.
                }
            }

            // Iterate through each product (e.g., meat, meals) created by the recipe.
            foreach (Thing product in values)
            {
                if (contagionComp != null)
                {
                    CompContaminatedFood foodComp = product.TryGetComp<CompContaminatedFood>();

                    // If the product is a valid food/ingestible and the RNG roll succeeds.
                    if (foodComp != null && Rand.Chance(contagionComp.Props.contaminationChance))
                    {
                        // Transfer the specific disease from the worker to the food item.
                        foodComp.linkedDisease = contagionComp.Props.hediffToApply;
                    }
                    else if (foodComp == null)
                    {
                        // Debug warning to help modders ensure their items have the necessary component.
                        Log.Warning($"[Blaxer Studios] {product.Label} does not have CompContaminatedFood component!");
                    }
                }
                yield return product;
            }
        }
    }
}